# ===========================
# VET EXPERTS - BASE
# ===========================
spring.application.name=sistema-veterinaria

# Perfil activo (LOCAL)
spring.profiles.active=local

# ===========================
# Thymeleaf
# ===========================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===========================
# Servidor
# ===========================
server.port=8080
server.error.whitelabel.enabled=false