# ===============================
# CONFIGURACIÓN GENERAL
# ===============================
spring.application.name=sistema-veterinaria

# Puerto dinámico para Render
server.port=${PORT:8080}

# ===========================
# BASE DE DATOS PRODUCCIÓN
# ===========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect