# ===========================
# VET EXPERTS - Configuración
# ===========================
spring.application.name=sistema-veterinaria

# ===========================
# Base de datos MySQL (NUBE)
# ===========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===========================
# Thymeleaf
# ===========================
spring.thymeleaf.cache=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===========================
# Servidor (Render usa puerto dinámico)
# ===========================
server.port=${PORT:8080}
server.error.whitelabel.enabled=false
